#!/usr/bin/env python3
"""
Fetch NREL NSRDB satellite solar radiation data for SF calibration points.

Requires NREL_API_KEY environment variable (free: https://developer.nrel.gov/signup/)
Or create .env.local with NREL_API_KEY=your_key_here

Outputs updated satellite-data.ts to src/lib/satellite-data.ts
"""

import json
import os
import sys
import time
import urllib.request
import urllib.error

# Load API key from env or .env.local
API_KEY = os.environ.get("NREL_API_KEY")
if not API_KEY:
    env_file = os.path.join(os.path.dirname(__file__), "..", ".env.local")
    if os.path.exists(env_file):
        with open(env_file) as f:
            for line in f:
                line = line.strip()
                if line.startswith("NREL_API_KEY=") and not line.startswith("#"):
                    API_KEY = line.split("=", 1)[1].strip()
                    break

if not API_KEY or API_KEY == "your_key_here":
    print("Error: NREL_API_KEY not set. Get a free key at https://developer.nrel.gov/signup/")
    print("Set it via: export NREL_API_KEY=your_key  or add to .env.local")
    sys.exit(1)

# 20 calibration points across SF
POINTS = [
    ("Outer Sunset", 37.755, -122.495),
    ("Inner Sunset", 37.76, -122.468),
    ("Outer Richmond", 37.779, -122.49),
    ("Inner Richmond", 37.779, -122.464),
    ("Haight-Ashbury", 37.769, -122.448),
    ("Twin Peaks", 37.752, -122.448),
    ("Castro", 37.761, -122.435),
    ("Mission", 37.76, -122.415),
    ("Potrero Hill", 37.761, -122.4),
    ("Dogpatch", 37.759, -122.388),
    ("SOMA", 37.779, -122.395),
    ("Marina", 37.801, -122.437),
    ("Pacific Heights", 37.793, -122.435),
    ("Bernal Heights", 37.739, -122.416),
    ("Parkside", 37.744, -122.487),
    ("Presidio", 37.8, -122.465),
    ("Noe Valley", 37.75, -122.434),
    ("Glen Park", 37.734, -122.433),
    ("Excelsior", 37.726, -122.425),
    ("Bayview", 37.734, -122.39),
]

GHI_TO_HOURS = 365 / 0.6

def fetch_pvwatts(lat, lng):
    """Fetch solar data from PVWatts v8 API."""
    url = (
        f"https://developer.nrel.gov/api/pvwatts/v8.json"
        f"?api_key={API_KEY}"
        f"&lat={lat}&lon={lng}"
        f"&system_capacity=4&module_type=0&losses=0"
        f"&array_type=0&tilt=0&azimuth=180"
    )
    req = urllib.request.Request(url)
    resp = urllib.request.urlopen(req, timeout=30)
    return json.loads(resp.read())

def main():
    results = []
    raw_responses = []

    for i, (name, lat, lng) in enumerate(POINTS):
        print(f"[{i+1}/{len(POINTS)}] Fetching {name} ({lat}, {lng})...")
        try:
            data = fetch_pvwatts(lat, lng)
            raw_responses.append({"name": name, "lat": lat, "lng": lng, "response": data})

            outputs = data.get("outputs", {})
            solrad_monthly = outputs.get("solrad_monthly", [0]*12)
            solrad_annual = outputs.get("solrad_annual", 0)
            sunshine_hours = round(solrad_annual * GHI_TO_HOURS)

            results.append({
                "name": name,
                "lat": lat,
                "lng": lng,
                "ghiAnnual": solrad_annual,
                "ghiMonthly": solrad_monthly,
                "sunshineHours": sunshine_hours,
            })
            print(f"  GHI: {solrad_annual:.3f} kWh/m2/day, ~{sunshine_hours} sun hrs")
        except urllib.error.HTTPError as e:
            print(f"  ERROR: HTTP {e.code} - {e.reason}")
            if e.code == 429:
                print("  Rate limited. Waiting 60s...")
                time.sleep(60)
        except Exception as e:
            print(f"  ERROR: {e}")

        # Respect rate limits
        time.sleep(1)

    # Save raw JSON responses
    raw_path = os.path.join(os.path.dirname(__file__), "nrel_satellite_data.json")
    with open(raw_path, "w") as f:
        json.dump(raw_responses, f, indent=2)
    print(f"\nRaw data saved to {raw_path}")

    # Generate TypeScript file
    ts_path = os.path.join(os.path.dirname(__file__), "..", "src", "lib", "satellite-data.ts")
    lines = [
        '// NREL NSRDB PSM3 satellite solar radiation data for San Francisco',
        '// Source: PVWatts v8 API, NSRDB Physical Solar Model v3',
        '// Resolution: ~4km grid cells',
        '// GHI = Global Horizontal Irradiance (kWh/m2/day annual average)',
        '// Monthly GHI values capture actual fog/cloud patterns from satellite observations',
        '// Generated by scripts/fetch_nrel_data.py',
        '',
        'export interface SatelliteDataPoint {',
        '  name: string;',
        '  lat: number;',
        '  lng: number;',
        '  ghiAnnual: number;',
        '  ghiMonthly: number[];',
        '  sunshineHours: number;',
        '}',
        '',
        'const GHI_TO_HOURS = 365 / 0.6;',
        '',
        'export const satelliteData: SatelliteDataPoint[] = [',
    ]

    for r in results:
        monthly_str = ", ".join(f"{v:.2f}" for v in r["ghiMonthly"])
        lines.append(
            f'  {{ name: "{r["name"]}", lat: {r["lat"]}, lng: {r["lng"]}, '
            f'ghiAnnual: {r["ghiAnnual"]}, ghiMonthly: [{monthly_str}], '
            f'sunshineHours: {r["sunshineHours"]} }},'
        )

    lines.extend([
        '];',
        '',
        'export function interpolateGHI(lat: number, lng: number): number {',
        '  let weightedSum = 0;',
        '  let weightSum = 0;',
        '  for (const point of satelliteData) {',
        '    const dist = Math.sqrt((lat - point.lat) ** 2 + (lng - point.lng) ** 2);',
        '    if (dist < 0.001) return point.ghiAnnual;',
        '    const weight = 1 / (dist ** 2);',
        '    weightedSum += weight * point.ghiAnnual;',
        '    weightSum += weight;',
        '  }',
        '  return weightedSum / weightSum;',
        '}',
        '',
        'export function interpolateMonthlyGHI(lat: number, lng: number): number[] {',
        '  return Array.from({ length: 12 }, (_, i) => {',
        '    let weightedSum = 0;',
        '    let weightSum = 0;',
        '    for (const point of satelliteData) {',
        '      const dist = Math.sqrt((lat - point.lat) ** 2 + (lng - point.lng) ** 2);',
        '      if (dist < 0.001) return point.ghiMonthly[i];',
        '      const weight = 1 / (dist ** 2);',
        '      weightedSum += weight * point.ghiMonthly[i];',
        '      weightSum += weight;',
        '    }',
        '    return weightedSum / weightSum;',
        '  });',
        '}',
        '',
        'export function ghiToSunshineHours(ghi: number): number {',
        '  return Math.round(ghi * GHI_TO_HOURS);',
        '}',
        '',
    ])

    with open(ts_path, "w") as f:
        f.write("\n".join(lines))
    print(f"TypeScript data saved to {ts_path}")
    print(f"\nDone! {len(results)}/{len(POINTS)} points fetched successfully.")

if __name__ == "__main__":
    main()
